export { Login } from './AuthenticationPages/Login'
export { Signup } from './AuthenticationPages/Signup'
export { Home } from './Home/Home'
export { Explore } from './Explore/Explore'
export { Chats } from './Chats/Chats'
export { Bookmarks } from './Bookmarks/Bookmarks'
export { UserProfilePage } from './UserProfilePage/UserProfilePage'